import json
import re
from backend.fetcher import fetch_html
from backend.cleaner import clean_html
from backend.extractor import extract_content
from backend.logger import write_debug_log
from backend import db


def run_task(task_description: str) -> str:
    """
    Orchestrates a single task pipeline:
    1. If an explicit URL is embedded in task_description, fetches and cleans HTML.
    2. Otherwise, calls Gemini API with Google Search Grounding to perform web search.
    3. Returns JSON string containing task_title and extracted items.
    """
    raw_html = ""
    cleaned_text = ""
    result = ""

    # Check for embedded URL in task_description
    url_match = re.search(r'https?://[^\s]+', task_description)
    target_url = url_match.group(0) if url_match else None

    if target_url:
        print(f"[1/3] Fetching webpage: {target_url} ...")
        try:
            raw_html = fetch_html(target_url)
            write_debug_log(target_url, task_description, raw_html=raw_html, cleaned_text=cleaned_text, result=result)
        except Exception as e:
            error_msg = f"Error fetching URL '{target_url}': {e}"
            write_debug_log(target_url, task_description, raw_html=raw_html, cleaned_text=cleaned_text, result=result, error=error_msg)
            raise RuntimeError(error_msg) from e

        print("[2/3] Cleaning HTML content ...")
        cleaned_text = clean_html(raw_html)
        write_debug_log(target_url, task_description, raw_html=raw_html, cleaned_text=cleaned_text, result=result)

        if not cleaned_text:
            error_msg = f"Cleaned webpage content is empty for URL '{target_url}'."
            write_debug_log(target_url, task_description, raw_html=raw_html, cleaned_text=cleaned_text, result=result, error=error_msg)
            raise ValueError(error_msg)

        print(f"[3/3] Extracting information with Gemini AI for description: '{task_description}' ...\n")
        try:
            result = extract_content(task_description=task_description, cleaned_text=cleaned_text)
            write_debug_log(target_url, task_description, raw_html=raw_html, cleaned_text=cleaned_text, result=result)
            return result
        except Exception as e:
            error_msg = f"Error during AI extraction: {e}"
            write_debug_log(target_url, task_description, raw_html=raw_html, cleaned_text=cleaned_text, result=result, error=error_msg)
            raise RuntimeError(error_msg) from e
    else:
        print(f"[1/2] Performing Natural Language Web Search for description: '{task_description}' ...")
        try:
            result = extract_content(task_description=task_description)
            write_debug_log("Auto-Web-Search", task_description, raw_html="", cleaned_text="", result=result)
            return result
        except Exception as e:
            error_msg = f"Error during AI search execution: {e}"
            write_debug_log("Auto-Web-Search", task_description, raw_html="", cleaned_text="", result=result, error=error_msg)
            raise RuntimeError(error_msg) from e


def run_task_by_id(task_id: int) -> dict:
    """
    Fetches a task by ID, executes natural language search/extraction,
    automatically updates task.name from Gemini's generated task_title,
    updates task results, and returns the updated task dict.
    """
    task = db.get_task(task_id)
    if not task:
        raise ValueError(f"Task with ID {task_id} not found.")

    task_desc = task.get("task_description") or task.get("goal") or ""

    print(f"--- Running Task [{task['id']}] '{task['name']}' ---")
    try:
        res_text = run_task(task_description=task_desc)
        
        # Try updating task.name if task_title was generated by Gemini
        try:
            clean_raw = res_text.replace("```json", "").replace("```", "").strip()
            parsed = json.loads(clean_raw)
            generated_title = parsed.get("task_title")
            if generated_title and isinstance(generated_title, str) and generated_title.strip():
                db.update_task_details(
                    task_id=task["id"],
                    name=generated_title.strip(),
                    task_description=task_desc,
                )
        except Exception:
            pass

        db.update_task_result(
            task_id=task["id"],
            status="SUCCESS",
            result_json=res_text,
            error=None,
        )
        print(f"✓ Task [{task['id']}] completed successfully.\n")
    except Exception as e:
        error_msg = str(e)
        db.update_task_result(
            task_id=task["id"],
            status="FAILED",
            result_json=None,
            error=error_msg,
        )
        print(f"✗ Task [{task['id']}] failed: {error_msg}\n")

    return db.get_task(task_id)


def run_user_tasks(user_id: str) -> list[dict]:
    """
    Fetches all persistent tasks for a user, executes each task via run_task_by_id,
    and returns the list of updated tasks with latest results.
    """
    tasks = db.list_tasks(user_id)
    if not tasks:
        print(f"No persistent tasks found for user '{user_id}'.")
        return []

    print(f"Found {len(tasks)} task(s) for user '{user_id}'. Starting execution...\n")
    results = []

    for idx, task in enumerate(tasks, 1):
        print(f"[Task {idx}/{len(tasks)}]")
        updated_task = run_task_by_id(task_id=task["id"])
        if updated_task:
            results.append(updated_task)

    return results
